---
title: "analysing maf"
author: "Danie Fridljand"
date: "2022"
output: html_document
---


```{r warning=FALSE, message=FALSE}
library(tidyr)
library(IHW)
library(ggplot2)
library(cowplot)
theme_set(theme_cowplot())
library(scales)
# library(latex2exp)
library(dplyr)
# require(biomaRt)
set.seed(1)
options(bitmapType ="cairo")
```

```{r setup, include=FALSE, cache = FALSE}
knitr::opts_knit$set(root_dir = "/g/huber/users/fridljand/R/ihw-forest-paper/") # TODO
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
root_dir <- "/g/huber/users/fridljand/R/ihw-forest-paper/"
```

## downloaded maf
```{r loading_pvalues}
chr1_df <- readRDS(file.path(root_dir, "data/hqtl_chrom1_chrom2/chr1_subset.Rds")) %>% dplyr::select(SNP, gene, pvalue)
chr2_df <- readRDS(file.path(root_dir, "data/hqtl_chrom1_chrom2/chr2_subset.Rds")) %>% dplyr::select(SNP, gene, pvalue)
```

```{r, eval = T}
chr1_maf <- readRDS(file = file.path(root_dir, "data/downloaded_covariates/chr1_maf.Rds"))
chr2_maf <- readRDS(file = file.path(root_dir, "data/downloaded_covariates/chr2_maf.Rds"))
```

Many MAFs are not available on `Biomart`. 
```{r}
chr1_maf_missing <- sum(is.na(chr1_maf$minor_allele_freq)) / nrow(chr1_maf)
chr2_maf_missing <- sum(is.na(chr2_maf$minor_allele_freq)) / nrow(chr2_maf)

paste0(round(100 * chr1_maf_missing, 2), "%")
paste0(round(100 * chr2_maf_missing, 2), "%")
```

For IHW, missing covariates are not allowed. So we conservatively replace all `NA`s with 0. 
```{r}
chr1_df <- chr1_df %>% left_join(chr1_maf, by = c("SNP" = "refsnp_id"))
chr2_df <- chr2_df %>% left_join(chr2_maf, by = c("SNP" = "refsnp_id"))
```

```{r}
chr1_df <- chr1_df %>% na.omit(minor_allele_freq)
#chr1_df <- chr1_df %>% mutate(minor_allele_freq = replace_na(minor_allele_freq, 0))
chr1_df$covariate <- rank(chr1_df$minor_allele_freq)/nrow(chr1_df)
```

```{r}
# set up data frame for ggplotting
ggplot(chr1_df, aes(x = covariate, y = -log10(pvalue))) + geom_hex(bins = 100) + 
    ylab(expression(-log[10]~p))
```
```{r}
ggplot(chr1_df, aes(x = pvalue)) + geom_histogram(boundary = 0)

```

```{r}
chr1_df$mafGroup <- groups_by_filter(chr1_df$minor_allele_freq, 8)

ggplot(chr1_df, aes(x=pvalue)) + 
  geom_histogram(boundary = 0) +
  facet_wrap( ~ mafGroup, nrow = 2)
```

# sampel minor alle frequency

```{r loading_pvalues2}
chr1_df <- readRDS(file.path(root_dir, "data/hqtl_chrom1_chrom2/chr1_subset.Rds")) %>% dplyr::select(SNP, gene, pvalue)
chr2_df <- readRDS(file.path(root_dir, "data/hqtl_chrom1_chrom2/chr2_subset.Rds")) %>% dplyr::select(SNP, gene, pvalue)
```

```{r, eval = T}
chr1_maf <- readRDS(file = file.path(root_dir, "data/hqtl_chrom1_chrom2/chr1_maf_sample.rds"))
chr2_maf <- readRDS(file = file.path(root_dir, "data/hqtl_chrom1_chrom2/chr2_maf_sample.rds"))
```

```{r}
chr1_df <- chr1_df %>% left_join(chr1_maf, by = c("SNP" = "refsnp_id"))
chr2_df <- chr2_df %>% left_join(chr2_maf, by = c("SNP" = "refsnp_id"))
```

```{r}
chr1_df$covariate <- rank(chr1_df$minor_allele_freq)/nrow(chr1_df)
range(chr1_df$covariate)
```

```{r}
# set up data frame for ggplotting
ggplot(chr1_df, aes(x = covariate, y = -log10(pvalue))) + geom_hex(bins = 100) + 
    ylab(expression(-log[10]~p))
```
```{r}
ggplot(chr1_df, aes(x = pvalue)) + geom_histogram(boundary = 0)

```

```{r}
chr1_df$mafGroup <- groups_by_filter(chr1_df$minor_allele_freq, 8)

ggplot(chr1_df, aes(x=pvalue)) + 
  geom_histogram(boundary = 0) +
  facet_wrap( ~ mafGroup, nrow = 2)
```
