---
title: "adapt_wrapper_vigniette"
format: html
editor: visual
---

```{r}
devtools::load_all("IHWForestPaper/adaptMT")
```

https://github.com/ryurko/adaptMT/blob/master/R/adapt-wrappers.R#L266

```{r}
set.seed(0)
 m <- 100
 n <- 1000
 x <- matrix(runif(n * m), n, m)
#'
#' # Generate the parameters from a conditional two-group
#' # logistic-Gamma GLM  where pi(x) and mu(x) are both
#' # linear in x. pi(x) has an intercept so that the average
#' # of pi(x) is 0.3
 inv_logit <- function(x) {exp(x) / (1 + exp(x))}
 pi1 <- 0.3
 beta.pi <- c(3, 3, rep(0, m-2))
 beta0.pi <- uniroot(function(b){
     mean(inv_logit(x %*% beta.pi + b)) - pi1
 }, c(-100, 100))$root
 pi <- inv_logit(x %*% beta.pi + beta0.pi)
 beta.mu <- c(2, 2, rep(0, m-2))
 beta0.mu <- 0
 mu <- pmax(1, x %*% beta.mu + beta0.mu)
#'
#' # Generate p-values
 H0 <- as.logical(ifelse(runif(n) < pi, 1, 0))
 y <- ifelse(H0, rexp(n, 1/mu), rexp(n, 1))
 pvals <- exp(-y)

```

```{r}
# # Run adapt_xgboost
res <- adapt_xgboost(x, pvals, alphas = 0.1, nfits = 5)
```

```{r}
rejection_position <- res[["rejs"]][[100]]
rejections <- rep(0, n)
rejections[rejection_position] <- 1
rejections
```
