---
title: "plot_smooth_weight"
format: html
editor: visual
---

```{r, message = FALSE}
library("dplyr")
library("reshape2")
library("ggplot2")
library(here)
library(purrr)

devtools::load_all("/Users/default/Google Drive/currentDocumants/research/2022_IHW-Forest/Code/IHW")
#devtools::load_all("../../IHW")
#devtools::load_all("../IHWForestPaper")

options(bitmapType ="cairo")
```

```{r}
myPalette <- colorRampPalette(rev(RColorBrewer::brewer.pal(11, "Spectral")))
```

## generate data

Generate simulation from https://support.bioconductor.org/p/90005/#9137847.

```{r}
# test data
m_test <- 100
m <- 1e5
# nfolds <- 3
# folds <- sample(1:nfolds, m, replace = TRUE)
```

```{r}
prop_alt <- function(covariate.1, covariate.2) {
  1 / (1 + exp(-covariate.1))
  # 1 / (1 + exp(-1 * (3 * covariate.1 - 5)))
  # abs(sin(pi*covariate.1))
}
```

generate training data

```{r}
data_train <- data.frame(
  covariate.1 = runif(m, -1, 1),
  covariate.2 = runif(m, -1, 1)
)

#data_train <- expand.grid(
#  covariate.1 = seq(-1, 1, length.out = sqrt(m)),
#  covariate.2 = seq(-1, 1, length.out = sqrt(m))
#)

data_train <- data_train %>%
  mutate(
    prop_alt = prop_alt(covariate.1, covariate.2),
    Hs = rbinom(n(), size = 1, prop_alt),
    pvalue = ifelse(Hs,
      rbeta(n(), 0.25, 1),
      runif(n())
    )
  )
```

generate testing data to plot on grid

```{r}
data_test <- expand.grid(
  covariate.1 = seq(min(data_train$covariate.1), max(data_train$covariate.1), length.out = m_test),
  covariate.2 = seq(min(data_train$covariate.2), max(data_train$covariate.2), length.out = m_test)
)

data_test <- data_test %>% mutate(
  prop_alt = prop_alt(covariate.1, covariate.2),
  Hs = rbinom(n(), size = 1, prop_alt),
  pvalue = ifelse(Hs,
    rbeta(n(), 0.25, 1),
    runif(n())
  )
)
```

combine both

```{r}
data_train_test <- rbind(data_train, data_test)
folds <- c(rep(1, nrow(data_train)), rep(2, nrow(data_test)))
head(data_train_test)
```

## True contours

```{r}
data_true <- expand.grid(
  covariate.1 = seq(-1, 1, length.out = m_test),
  covariate.2 = seq(-1, 1, length.out = m_test)
)

data_true <- data_true %>%
  mutate(
    prop_alt = prop_alt(covariate.1, covariate.2),
    true_alt_expectation = 0.25 / (0.25 + 1),
    cond_exp = 0.5 + prop_alt * (0.5 - true_alt_expectation),
  )
```

This is not the same thing as the true weights. But the contours should be the same.

```{r}
ggplot(data_true, aes(x = covariate.1, y = covariate.2, color = cond_exp))+
  geom_point() +
  scale_colour_gradientn(colours = myPalette(100))
```

## Quantile

```{r, eval = TRUE}
groups_by_filter_multivariate_eval <- function(covariates_train, covariates_eval, nbins) {
  nvar <- ncol(covariates_train)
  nbin_dim <- max(1, floor(nbins ^ (1 / nvar))) #does not change anything, if nvar = 1
  
  groups <- lapply(seq_len(nvar), function(i) {
    covariate_train_i <- covariates_train[, i, drop = TRUE]
    covariates_eval_i <- covariates_eval[, i, drop = TRUE]
    
    breaks <- quantile(covariate_train_i, probs = seq(0, 1, length.out = nbin_dim+1), na.rm = TRUE)
    #add interval open to the right

    covariates_eval_i_binned <- cut(covariates_eval_i, breaks, include.lowest = TRUE, right = FALSE)
  })
  
  if(nvar == 1){
    groups <- unname(unlist(groups))
  }else{
    groups <- do.call(cbind, groups)
    groups <- apply(groups, 1, paste, collapse = "-") # base R equivalent of tidyr::unite
  }
  # convert to factor
  groups <- as.factor(groups)
  
  groups
}
```

```{r}
plot_weights_quantile_2d <- function(ihw_quantiles, m_test = 100,  fold = 1){
  ihw_quantiles_df <- ihw_quantiles@df
  
  #build grid to evaluate for plotting
  data_test <- expand.grid(
    covariate.1 = seq(min(ihw_quantiles_df$covariate.1), max(ihw_quantiles_df$covariate.1), length.out = m_test),
  covariate.2 = seq(min(ihw_quantiles_df$covariate.2), max(ihw_quantiles_df$covariate.2), length.out = m_test)
)
  
  covariates_train <- ihw_quantiles_df %>% select("covariate.1","covariate.2")
  
  data_test$groups <- groups_by_filter_multivariate(
  covariates_train = covariates_train, 
  covariates_test = data_test, 
  nbins = ihw_quantiles@nbins
)
  
  #relevel group labels
  levels(data_test$groups) <- seq_len(nlevels(data_test$groups))
  
  #obtain weights
  data_test$weight <- sapply(data_test$groups, function(group_i){
  ihw_quantiles@weights[group_i,fold]
})
  
  #plot everything
  plot <- data_test %>%
  ggplot(aes(x = covariate.1, y = covariate.2, color = weight))+
  geom_point()  +
  scale_colour_gradientn(colours = myPalette(100))
  
  plot
}
```

```{r}
ihw_quantiles <- ihw(formula = pvalue ~ covariate.1 + covariate.2, 
                  data = data_train, 
                  alpha = 0.1, 
                  stratification_method = "quantiles", 
                  seed = 1)

ihw_quantiles_df <- ihw_quantiles@df
```

plot_weights_quantile_2d(ihw_quantiles)

```{r}
plot_weights_quantile_2d(ihw_quantiles)
```

```{r}
data_test$groups <- groups_by_filter_multivariate(
  covariates_train = data_train %>% select("covariate.1","covariate.2"), 
  covariates_test = data_test %>% select("covariate.1","covariate.2"), 
  nbins = ihw_quantiles@nbins
)
```

```{r}
ihw_quantiles_df %>%
  ggplot(aes(x = covariate.1, y = covariate.2, color = group))+
  geom_point() 
```

```{r}
data_test %>%
  ggplot(aes(x = covariate.1, y = covariate.2, color = groups))+
  geom_point() 
```

Add groups deterministically for nicer plots

```{r}
levels(data_test$groups) <- seq_len(nlevels(data_test$groups))
```

```{r}
data_test$groups <- as.numeric(data_test$groups)
data_test$weight_deterministic <- sapply(data_test$groups, function(group_i){
  ihw_quantiles@weights[group_i,1]
} )
```

```{r}
ihw_quantiles_df %>%
  filter(fold == 1) %>%
  ggplot(aes(x = covariate.1, y = covariate.2, color = weight))+
  geom_point() +
  scale_colour_gradientn(colours = myPalette(100))
```

```{r}
data_test %>%
  ggplot(aes(x = covariate.1, y = covariate.2, color = weight_deterministic))+
  geom_point()  +
  scale_colour_gradientn(colours = myPalette(100))
```

## Tree

```{r}
ihw_tree <- ihw(formula = pvalue ~ covariate.1 + covariate.2, 
                  data = data_train_test, 
                  alpha = 0.1, 
                  stratification_method = "forest", 
                  folds = folds, 
                  ntrees = 1, 
                  n_censor_thres = 1, 
                  nodedepth = 3, 
                  nodesize = 1000, 
                  seed = 1)

ihw_tree_df_test <- ihw_tree@df %>%
  filter(fold == 2)
```

```{r}
ggplot(ihw_tree_df_test, aes(x = covariate.1, y = covariate.2, color = weight))+
  geom_point() +
  scale_colour_gradientn(colours = myPalette(100))
```

## Forest

```{r}
ihw_forest <- ihw(formula = pvalue ~ covariate.1 + covariate.2, 
                  data = data_train_test, 
                  alpha = 0.1, 
                  stratification_method = "forest", 
                  folds = folds, 
                  ntrees = 3, 
                  n_censor_thres = 3, 
                  nodedepth = 3, 
                  nodesize = 1000, 
                  seed = 1)

ihw_forest_df_test <- ihw_forest@df %>%
  filter(fold == 2)
```

```{r}
ggplot(ihw_forest_df_test, aes(x = covariate.1, y = covariate.2, color = weight))+
  geom_point() +
  scale_colour_gradientn(colours = myPalette(100))
```
