---
title: "Boca Leek IHW Benchmark"
author: "Daniel Fridljand"
date: "`r Sys.Date()`"
#output: rmarkdown::html_vignette
header-includes:
   - \usepackage{bbm}
output: html_document
---

## Preperation
First some cleaning and basic packages.
analog to http://bioconductor.org/packages/release/data/experiment/vignettes/IHWpaper/inst/doc/hqtl_IHW_BY.html 
```{r setup, message = F}
library(magrittr)
library(dplyr)
library(ggpubr)
library(ggplot2)
library(cowplot)
library(RColorBrewer)
knitr::opts_chunk$set(echo = TRUE)

set.seed(123)
theme_set(theme_cowplot())
library(IHW)
options(bitmapType ="cairo")
```

## Colors and method names used throughout 


## Load files

```{r, eval = T}
#chr1_df <- readRDS(file = "precomputed_results/chr1_df.Rds")
#chr2_df <- readRDS(file = "precomputed_results/chr1_df.Rds")

chr1_df <- readRDS(file = "/g/huber/users/fridljand/R/ihw-forest-paper/precomputed_results/chr1_df.Rds")
chr2_df <- readRDS(file = "/g/huber/users/fridljand/R/ihw-forest-paper/precomputed_results/chr1_df.Rds")

file_loc <- "/g/huber/users/fridljand/R/ihw-forest-paper/data/hqtl_chrom1_chrom2/"
ms_chr1 <- readRDS(file.path(file_loc, "m_groups_chr1.Rds"))
ms_chr2 <- readRDS(file.path(file_loc, "m_groups_chr2.Rds"))
```

```{r, eval=F}
chr1_df <- chr1_df[seq_len(1e5), ]
chr2_df <- chr2_df[seq_len(1e5), ]
```

```{r}
chr1_chr2_df <- rbind(chr1_df, chr2_df)
chr1_chr2_cov <- chr1_chr2_df %>% select(starts_with("cov"))
chr1_chr2_cov <- as.matrix(chr1_chr2_cov)

folds_vec <- as.factor(c(rep(1, nrow(chr1_df)), rep(2, nrow(chr2_df))))

m_groups <- cbind(ms_chr1, ms_chr2)
m <- sum(m_groups)# This is really really important, do not do m <- nrow(chr1_chr2_df)
alpha <- .01 / (log(m) + 1)
```


```{r}
rej_bh <- sum(p.adjust(chr1_chr2_df$pvalue, n = m, method = "BH") <= alpha)
rej_bh #TODO should be 9110
```

```{r, eval = T}
#chr1_chr2_cov_test <- chr1_chr2_cov[,1, drop = TRUE] #TODO 
ihw_quantile <- ihw(chr1_chr2_df$pvalue, chr1_chr2_df$cov_dist, alpha = alpha)

#ihw_quantile <- ihw(chr1_chr2_df$pvalue, chr1_chr2_df$cov_dist, alpha = alpha, folds = folds_vec, stratification_method = "quantiles",
#                     null_proportion = F)

saveRDS(ihw_quantile, file = "/g/huber/users/fridljand/R/ihw-forest-paper/precomputed_results/ihw_quantile.Rds")
rejections(ihw_quantile)

#sorted_adj_p <- p.adjust(weighted_pvalues(ihw_quantile), method = "BH", n = m)
#sorted_adj_p <- p.adjust(weighted_pvalues(ihw_quantile), method = "BH", n = nrow(chr1_chr2_df))
#sum(sorted_adj_p <= alpha)
```

```{r}
IHW::adj_pvalues(ihw_quantile) <= alpha
```

```{r}
ntrees <- 1L # number of trees per forest
ntaus <- 1

nsplit <- 3
maxdepth <- 3 # 3 worked well!
nodesize <- 1200
```

```{r, eval = T}
chr1_chr2_cov_test <- chr1_chr2_cov[,1] #TODO 
ihw_forest <- ihw(chr1_chr2_df$pvalue, chr1_chr2_cov_test, alpha = alpha, folds = folds_vec, stratification_method = "forest", ntrees = ntrees,
                    nsplit=nsplit, ntaus = ntaus, maxdepth = maxdepth, nodesize = nodesize,
                     null_proportion = F)

saveRDS(ihw_forest, file = "/g/huber/users/fridljand/R/ihw-forest-paper/precomputed_results/ihw_forest.Rds")
rejections(ihw_forest)
```


```{r, eval = T}
ihw_forest <- readRDS(file = "/g/huber/users/fridljand/R/ihw-forest-paper/precomputed_results/ihw_forest.Rds")
```

```{r}
#TODO 
head(groups_factor(ihw_forest))
groups_factor <- groups_factor(ihw_forest)[, 1, drop = TRUE]
class(groups_factor)
ihw_forest2 <- ihw(chr1_chr2_df$pvalue, groups_factor, alpha = alpha, folds = folds_vec, covariate_type = "nominal")
```

```{r}
rej_forest <- rejections(ihw_forest)
ihw_forest2 <- rejections(ihw_forest2)
rej_bh
ihw_forest
ihw_forest2
```

