---
title: "Boca Leek IHW Benchmark"
output: html_document
---

## Preperation
First some cleaning and basic packages.
```{r setup, message = F}
library(magrittr)
library(dplyr)
library(ggpubr)
library(ggplot2)
library(cowplot)
knitr::opts_chunk$set(echo = TRUE)

set.seed(123)
theme_set(theme_cowplot())
alpha = 0.1
```


```{r}
noise_sim_res <-readRDS(file="../precomputed_results/noise_sim.Rds")
noise_sim_res <- noise_sim_res %>% mutate(method = forcats::fct_recode(method,
"IHW-Quantile"= "IHW-quantile",
"IHW-Forest" ="IHW-forest" ))
```

```{r, message=FALSE, warning=FALSE}
noise_sim_res <- noise_sim_res %>%
  group_by(dimension, method) %>%
  summarize(
    FDR = mean(FDP, na.rm = TRUE),
    Power = mean(pow, na.rm = TRUE),
    n_monte_carlo = sum(!is.na(FDP)),
    pow_se = sd(pow, na.rm = TRUE) / sqrt(n_monte_carlo)
  ) %>%
  ungroup()
```

```{r}
 noise_sim_res_FDR <- ggplot(noise_sim_res, aes_string(x = "dimension", y = "FDR", shape = "method", col = "method")) +
  geom_line() +
  geom_point() +
  geom_hline(yintercept = alpha, linetype = 2) +
  guides(color=guide_legend(title="Method", legend.text=element_text(size=4)),
         shape =  "none")+
   scale_x_continuous(breaks= scales::pretty_breaks())#+
   #scale_color_manual(values = c("#00AFBB", "#52854C", "#FC4E07"))# fill=guide_legend(nrow=2,byrow=TRUE)
noise_sim_res_FDR
```

```{r}
noise_sim_res_power <- ggplot(noise_sim_res, aes_string(x = "dimension", y = "Power", shape = "method", col = "method")) +
  geom_line() +
  geom_point()  +
  ylab("Power")+
  guides(color=guide_legend(title="Method", legend.text=element_text(size=4)))+
  scale_x_continuous(breaks= scales::pretty_breaks())#+
   #scale_color_manual(values = c("#00AFBB", "#52854C", "#FC4E07"))
noise_sim_res_power
```

```{r}
g_combined<- ggarrange(noise_sim_res_FDR, noise_sim_res_power, nrow = 1, widths = c(1, 1), common.legend = TRUE, legend = "bottom") 

#g_combined <- annotate_figure(g_combined, top = text_grob("ifelse(sum(cov_row[1]^2) <= 1, 0.9, 0)", 
#               color = "red", face = "bold", size = 14))
g_combined
ggplot2::ggsave("figures/noise_sim.png", g_combined,
                width = 5, height = 3.25)

```

