---
title: "Multiple testing with continuous covariates"
author: "Nikos Ignatiadis"
date: "`r doc_date()`"
output:
  BiocStyle::html_document
vignette: >
    %\VignetteEngine{knitr::rmarkdown}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup

### Load packages

```{r  message=FALSE,result=FALSE, warning=FALSE}
library(tidyverse)
library(ggplot2)
library(cowplot)
library(RColorBrewer)
```

## Colors and method names used throughout 

```{r}
# (from https://github.com/dill/beyonce)
beyonce_colors <- c("#b72da0", "#7c5bd2", "#0097ed","#00c6c3",
                    "#9cd78a", "#f7f7a7", "#ebab5f", "#e24344",
                    "#04738d")#,"#d8cdc9")
beyonce_colors[6] <- c("#dbcb09") # thicker yellow
pretty_colors <- beyonce_colors[c(2,1,3:5)]
```

```{r}
#method_names <- c("BH", "Clfdr-oracle", "Clfdr-EM", "AdaPT", "IHW-Storey-BetaMix", "IHW-BH-Grenander")
method_names <- c("BH","Clfdr-EM", "AdaPT", "IHW-Forest", "IHW-BH-Grenander")
method_names_print <- c("BH", "Clfdr", "AdaPT",  "IHW-Forest", "IHW")

method_colors <- c("Black", beyonce_colors[c(3,4, 2, 1)])
names(method_colors) <- method_names_print
method_shapes <- c(20, 1, 2, 12, 13)
names(method_shapes) <- method_names_print

```

# Main simulation

## Load result files

```{r}
betamix_r <-readRDS(file="../precomputed_results/betamix_simulations.Rds")
betamix_r_forest <-readRDS(file="../precomputed_results/evaluated_betamix_sim_forest.Rds")
betamix_r <- append(betamix_r, betamix_r_forest)
```

```{r}
betamix_res <-  bind_rows(betamix_r) %>% 
  group_by(method, m, mu_slope) %>%
  summarize(FDR = mean(FDP, na.rm=TRUE),
            Power=mean(pow, na.rm=TRUE),
            n=sum(!is.na(FDP)),
            se_power = sd(pow, na.rm=TRUE)/sqrt(n)) %>%
  arrange(mu_slope, desc(Power)) %>% 
  filter(method %in% method_names) %>%
  ungroup()  %>%
  mutate(method = as.factor(method)) %>%
  mutate(method = fct_recode(method,
    "IHW" = "IHW-BH-Grenander",
    "Clfdr" = "Clfdr-EM"
  ))
```

## Plot FDR

```{r width=6/1.2,height=4/1.2}
fdr_betamix_plot <- ggplot(betamix_res, aes(x=mu_slope, y=FDR,shape=method, col=method)) + 
  geom_line() + geom_point() + 
  ylim(0, 0.15) + 
  scale_color_manual(values=method_colors)+
  scale_shape_manual(values=method_shapes)+
  geom_hline(yintercept=0.1, linetype=2)+
  xlab(expression(bar(beta)))+
  theme_cowplot() +
  theme(legend.position = "none")

fdr_betamix_plot
```

```{r}
ggsave(fdr_betamix_plot, filename="fdr_betamix.pdf", width=6/1.2,height=4.2)
```

## Plot Power

```{r width=7.73/1.2,height=4/1.2}
power_betamix_plot <- ggplot(betamix_res, aes(x=mu_slope, y=Power, shape=method, col=method)) + 
  geom_line() + geom_point() + 
  scale_color_manual(values=method_colors)+
  scale_shape_manual(values=method_shapes)+
  xlab(expression(bar(beta)))+
  scale_y_log10(breaks = c(0.003, 0.01, 0.025, 0.05, 0.1, 0.2, 0.4)) + 
  ylab("Power (log scale)") + 
  theme_cowplot()  +
  theme(legend.title=element_blank())  

power_betamix_plot
```
```{r}
power_betamix_plot <- power_betamix_plot + guides(colour = guide_legend(nrow = 2))
legend_betamix <- get_legend(power_betamix_plot)
legend_betamix <- ggpubr::as_ggplot(legend_betamix)
ggsave(legend_betamix, filename = "legend_betamix.pdf", width = 3.4, height = 2.8)
legend_betamix
```

```{r eval=T}
power_betamix_plot <- power_betamix_plot + theme(legend.position = "none")
#ggsave(power_betamix_plot, filename="power_betamix_nolegend.pdf", width=6/1.2,height=4/1.2)
ggsave(power_betamix_plot, filename="power_betamix.pdf",  width=6/1.2,height=4.2)
```