---
title: "qplot"
author: "Daniel"
date: "09/05/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(magrittr)
options(bitmapType ="cairo")
```

## Including Plots

```{r pressure, echo=FALSE}
n <- 100

covariate <- rnorm(n)
covariate_quant <- rank(covariate)/n
qplot <- ggplot(data = data.frame(covariate, covariate_quant), aes(x = covariate, y = covariate_quant)) + 
  geom_point() +
  xlab("X1") +
  ylab("quantile %") +
  theme_classic()

qplot
ggplot2::ggsave("../figures/qplot.png", qplot,
  width = 5, height = 3.25
)
```

```{r, eval = F, include=FALSE}
covariate <- matrix(rnorm(99), ncol = 3)
covariate <- as.data.frame(covariate)
names(covariate) <- c("X1","X2", "X3")
covariate<- covariate %>% dplyr::slice(1:3)
  

# Plain latex output 
knitr::kable(covariate, "latex")
  #knitr::kbl(caption = "Example", # Adding caption  
  #      format = "latex") #%>% # Output format = latex 
   # knitr::kable_classic(html_font = "Cambria") # Font = Cambria 
```

```{r}
ihw_quantile <- ihw(Ps, Xs, alpha)
ihw_forest <- ihw(Ps, Xs, alpha, stratification_method = "forest")
```

```{r}
t<- round(runif(3),1) 
3*t/ sum(t)
```

