---
title: "tree_20211204"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr) # data wrangling
library(rpart) # performing regression trees
library(rpart.plot) # plotting regression trees

set.seed(1)
```

## R Markdown
```{r set parameters}
m <- 20000
nfolds <- 5
nbins <- 5
# tree specific parameters
minbucket <- floor(m / (3 * nbins)) # todo smaller trees are ok for forest
maxdepth <- log2(nbins)
```

```{r generate data}
Xs <- runif(m, min = 0, max = 2.5) # covariate
Hs <- rbinom(m, 1, 0.6) # hypothesis true or false
Zs <- rnorm(m, Hs * Xs) # Z-score
sorted_folds <- sample(1:nfolds, m, replace = TRUE)
Ps <- 1 - pnorm(Zs) # pvalue
# todo rename Ps to be more consistent
```


```{r create art response, echo=FALSE}
# regression tree
tau <- 0.9 # https://www.biorxiv.org/content/10.1101/035675v4.full.pdf fixed thresholds between 0.8 and 0.95 are often used.
Ys <- (Ps >= tau) / (1 - tau)
```

```{r grow tree for each fold, echo=FALSE}
data <- data.frame(Ys, Xs, sorted_folds)
fold_trees <- lapply(1:nfolds, function(i) {
  data_other_folds <- data[sorted_folds != i, ]

  # grow tree
  tree_holdout_fold <- rpart(
    formula = Ys ~ Xs,
    data    = data_other_folds,
    method  = "anova",
    control = rpart.control(cp = 0, minbucket = minbucket, maxdepth = maxdepth)
  )

  return(tree_holdout_fold)
})
```

#```{r plot first tree, echo=FALSE}
#rpart.plot(fold_trees[[1]])
#```
Number of nodes per tree
```{r run some diagnosis on trees, echo=FALSE}
sapply(fold_trees, function(tree) {
  length(unique(tree$where))
})
```

```{r find leaves, echo=FALSE}
data$groups <- NA
for(i in 1:nfolds){
  data_holdout_fold <- data[sorted_folds == i, ]
  tree_holdout_fold <- fold_trees[[i]]

  # https://stackoverflow.com/questions/9797447/rpart-node-assignment
  tree_holdout_fold2 <- partykit::as.party(tree_holdout_fold) # TODO is this necessary?

  #groups <- predict(tree_holdout_fold2, newdata = data_holdout_fold, type = "node")
  data[sorted_folds == i, "groups"] <- predict(tree_holdout_fold2, newdata = data_holdout_fold, type = "node")
}
```

```{r}
table(data$sorted_folds, data$groups)
```
```{r}
intervals <- data %>%
  group_by(sorted_folds, groups) %>%
  summarise(min = min(Xs), max = max(Xs)) %>%
  mutate(min = round(min, 1), max = round(max,1),
    conc = paste(min, max))
```

