---
title: "Boca Leek IHW Benchmark"
output: html_document
---

```{r setup, include=FALSE}
# clear memory
rm(list = ls(all = TRUE))

library(magrittr)
knitr::opts_chunk$set(echo = TRUE)
set.seed(123)

```

```{r load_functions, echo = F,  message = F, eval = T}
source("/Volumes/fridljand/R/IHW/bioconductor/R/helpers.R")
source("/Volumes/fridljand/R/IHW/bioconductor/R/ihw_convex_20211214.R")
source("/Volumes/fridljand/R/IHW/bioconductor/R/ihw_class.R")
source("/Volumes/fridljand/R/IHW/bioconductor/R/weights.R")
```

```{r load_functions, echo = F,  message = F, eval = FALSE}
source("/Users/default/Downloads/IHW/R/helpers.R")
source("/Users/default/Downloads/IHW/R/ihw_class.R")
source("/Users/default/Downloads/IHW/R/ihw_convex.R")
source("/Users/default/Downloads/IHW/R/weights.R")
```

```{r set_parameters3}
lambda <- Inf
alpha <- .1
tau <- 0.7 # censoring parameter for BocaLeek estimator
ntrees <- 10 # number of trees per forest
```

## 4. real data 
http://bioconductor.org/packages/release/bioc/vignettes/IHW/inst/doc/introduction_to_ihw.html
```{r, load_airway, message = F, echo = F}
library("DESeq2")
library("dplyr")
data("airway", package = "airway")
dds <- DESeqDataSet(se = airway, design = ~ cell + dex) %>% DESeq
deRes <- as.data.frame(results(dds))
```

```{r}
m <- nrow(deRes)
nfolds <- 3
folds <- sample(1:nfolds, m, replace = TRUE)
```

```{r}
ihwRes <- ihw(pvalue ~ baseMean,  data = deRes, alpha = alpha, folds = folds,  lambda = lambda, use_forest = FALSE)
#ihwRes <- ihw(deRes$pvalue,  deRes$baseMean, alpha = alpha, folds = folds,  lambda = lambda, use_forest = FALSE) 
```

```{r}
ihwRes <- ihw(pvalue ~ baseMean,  data = deRes, alpha = alpha, folds = folds, use_forest = TRUE, ntrees = ntrees, tau = tau, lambda = lambda)
```
