---
title: "bocaleek_tree20211207"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#Rcpp::sourceCpp("/g/huber/users/fridljand/R/IHW/bioconductor/C++/grenador.cpp")
Rcpp::sourceCpp("/Volumes/fridljand/R/IHW/bioconductor/C++/grenador.cpp")
```

## R Markdown


```{r load functions, echo = F, include=FALSE}
script.dir <- "/Volumes/fridljand/R/IHW/bioconductor/R"
#script.dir <- "/g/huber/users/fridljand/R/IHW/bioconductor/R"

scripts <- list.files(script.dir)
lapply(scripts, function(script) {source(file.path(script.dir, script))})
```

## Including Plots

You can also embed plots, for example:

```{r generate data, echo=FALSE}
m <- 20000
nfoldsI <- 3
X1 <- runif(m, min = 0, max = 2.5) # covariate
X2 <- runif(m, min = 0, max = 2.5) # covariate
X<- cbind(X1, X2)
H <- rbinom(m, 1, 0.1) # hypothesis true or false
Z <- rnorm(m, H * (X1+X2)) # Z-score
# .Random.seed <- save.seed
pvalue <- 1 - pnorm(Z) # pvalue

folds <- sample(1:nfoldsI, m, replace = TRUE)
adjustment_type<- "BH" #"bonferroni" "BH" 
```

```{r create fdp eval }
#' Evaluate multiple testing procedure
#
#' @param Hs Vector with indicators of alternatives (1) and true nulls (0)
#' @param rjs Vector with indicator of rejected hypotheses
#' @return Data frame with columns `rjs` (total rejections), `pow` (Power), `FDP` (False discovery proportion)
#' @export
fdp_eval <- function(Hs, rjs){
  rjs_total <- sum(rjs)
  pow <- sum(rjs*Hs)/max(1,sum(Hs))
  FDP <- sum(rjs*(1-Hs))/max(1,rjs_total)
  FWER <- sum( (1-Hs)*rjs) > 0
  data.frame(rjs=rjs_total, pow=pow, FDP=FDP, FWER=FWER)
}
```

```{r run IHW}
ihw_fdr_no_forest <- ihw(pvalue, X, alpha =.1, folds = folds, use_forest = FALSE, lp_solver = "algorithm5") 
```


```{r run_IHW_forest}
#TODO ntrees > 1 => how to as.factor
taus <- seq(0.5, 0.9, length.out = 20) 
tau <- 0.6473684
tau <- 0.7
#ihw_fdr_forests <- lapply(taus, function(tau){
ihw_fdr_forests <- list()
#for(tau in taus){
  ihw_fdr_forest <- ihw(pvalue, X, alpha =.1, folds = folds, use_forest = TRUE, ntrees = 10, tau = tau, lp_solver = "lpsymphony", lambda = Inf)  #, lambda = Inf
  ihw_fdr_forests <- append(ihw_fdr_forests, ihw_fdr_forest) 
#}
  
#})
```

```{r fdp_eval}
fdp_eval_no_forest <- fdp_eval(H, IHW::rejected_hypotheses(ihw_fdr_no_forest))
fdp_eval_forests <- lapply(ihw_fdr_forests, function(ihw_fdr_forest){
  fdp_eval_forest <- fdp_eval(H, IHW::rejected_hypotheses(ihw_fdr_forest))
})
fdp_eval_forests <- do.call(rbind, fdp_eval_forests)
test <- rbind(fdp_eval_no_forest,
      fdp_eval_forests)
```

```{r}
ihw_fdr_official <- IHW::ihw(pvalue, X, alpha =.1, folds = folds) 
```


