---
title: "tree_20211204"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr) # data wrangling
library(rpart) # performing regression trees
library(rpart.plot) # plotting regression trees

library(ranger)
set.seed(1)
```

## R Markdown
```{r set parameters}
m <- 20000
nfolds <- 5
nbins <- 5
ntrees <- 10
seed <- 1
# tree specific parameters
minbucket <- floor(m / (3 * nbins)) # todo smaller trees are ok for forest
```

```{r generate data}
covariate <- runif(m, min = 0, max = 2.5) # covariate
Hs <- rbinom(m, 1, 0.6) # hypothesis true or false
Zs <- rnorm(m, Hs * covariate) # Z-score
sorted_folds <- sample(1:nfolds, m, replace = TRUE)
pvalues <- 1 - pnorm(Zs) # pvalue
# todo rename Ps to be more consistent
```

The input parameters are nfolds nbins ntrees seed covariate Ps sorted_folds

```{r Pseudo calculation}
maxdepth <- log2(nbins)
maxdepth <- ceiling(maxdepth)
min.node.size <- 2^(maxdepth + 1) - 1
```


```{r create art response, echo=FALSE}
# regression tree
tau <- 0.9 # httpvalues://www.biorxiv.org/content/10.1101/035675v4.full.pdf fixed thresholds between 0.8 and 0.95 are often used.
indic <- (pvalues >= tau) / (1 - tau) # binary indicator from Boca and leek
```

```{r grow tree for each fold, echo=FALSE}
data <- data.frame(indic, covariate, sorted_folds)
forest_fold <- lapply(1:nfolds, function(i) {
  data_other_folds <- data[sorted_folds != i, ]

  forest_other_fold <- ranger::ranger(
    formula = indic ~ covariate,
    data = data_other_folds,
    num.trees = ntrees,
    mtry = 1,
     regularization.factor = 1e-30,
    # regularization.usedepth = TRUE,
    max.depth = maxdepth,
    splitrule = "variance",
    importance = "none",
    seed = seed
  )

  return(forest_other_fold)
})
```

```{r plot sample tree}
# httpvalues://stats.stackexchange.com/questions/41443/how-to-actually-plot-a-sample-tree-from-randomforestgettree
treeInfo(forest_fold[[1]], 2)
```

```{r plot sample tree}
# https://stats.stackexchange.com/questions/41443/how-to-actually-plot-a-sample-tree-from-randomforestgettree
sum(treeInfo(forest_fold[[1]], 1)$terminal)
```

```{r find nodes, echo=FALSE}
# does not work for forest anymore
groups <- matrix(0, nrow = nrow(data), ncol = ntrees)

for (i in 1:nfolds) {
#i <- 1
  data_holdout_fold <- data[sorted_folds == i, ]
  forest_other_fold <- forest_fold[[i]]

  # https://stackoverflow.com/questions/9797447/rpart-node-assignment

  predict_groups <- predict(forest_other_fold,
    predict.all = TRUE,
    data = data_holdout_fold,
    type = "terminalNodes"
  )
  
  groups[sorted_folds == i, ] <- predict_groups$predictions
}
groups
```


```{r enumerate leaves instead of nodes}
groups4 <- factor(groups)
dim(groups4) <- dim(groups)
groups4

levels(groups4)

groups5 <- as.data.frame(groups)
```

```{r}
levels_nodes <- apply(groups, 2, function(col) {
  col <- as.factor(col)
  levels <- levels(col)
  levels(col) <- seq_along(levels)
  return(col)
})

dim(levels_nodes) <- dim(groups)
```

```{r}
X <- 3
nm1 <- names(dt)
dt[letters[seq_len(X)]] <- 0
dt[c(setdiff(names(dt), nm1), nm1)]
```
