          ---
title: "regul_weight"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
thresholds_to_weights <- function(ts, m_groups) {
  if (length(ts) != length(m_groups)) stop("incosistent number of elements for ts and m_groups")

  nbins <- length(ts)
  m <- sum(m_groups)

  if (all(ts == .0)) {
    rep(1, nbins)
  } else {
    ts * m / sum(m_groups * ts)
  }
}
```

```{r input_par}
gamma <- 0.5
G <- 5

ws <- runif(G, 0, 2)
m_groups <- runif(G, 0, 200)
ws <- thresholds_to_weights(ws, m_groups)
# TODO sort ws!
```

Introduces package dependency on stats. We want to keep it simple!
#TODO negative binomial!
https://keisan.casio.com/exec/system/1180573211
Negative hypergeometric distribution
https://en.wikipedia.org/wiki/Negative_hypergeometric_distribution

```{r}
dnhyper <- function(x, k, gamma, g) {
  n <- k + gamma
  r <- g * (n - k + 1) / k
  r <- floor(r)
  a <- choose(x + r - 1, x)
  b <- choose(n - r - x, k - x)
  c <- choose(n, k)
  res <- a * b / c
  #TODO vectorize case_when
  if(is.nan(res)){
    return(g== x)
  }else if(abs(res)<1e-15){
    return(0)
  }else{
    return(res)
  }
}
```

```{r}
gamma <- 0
k <- (G-1)
gg <- 0:(G-1)
xx <- 0:(G-1)

matrix <- matrix(0, nrow = G, ncol = G)
for(i in seq_along(gg)){
  for(j in seq_along(xx)){
    g <- gg[i]
    x <- xx[j]
    matrix[i,j] <- dnhyper(x, k, gamma, g)
  }
}
matrix
```
for fixed g, this should be 1
```{r}
colSums(matrix)
```

